ALTER TABLE `Plan` ADD COLUMN `hasSpotlight` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasStatistics` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasWhatsapp` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `maxPhotos` INTEGER NULL,
    ADD COLUMN `maxVideos` INTEGER NULL;